version: 2
jobs:

  mdl:
    docker:
      - image: rsrchboy/mdl
    steps:
      - checkout
      - run: mdl .

  flake8:
    docker:
      - image: python
    steps:
      - checkout
      - run: pip install flake8
      - run: flake8 --ignore=E722 http-daemon-with-db

  build-go-ethereum:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run: docker info
      - run: docker build -t lolo/go-ethereum go-ethereum
      - run: docker run lolo/go-ethereum version

  build-http-daemon-with-db:
    docker:
      - image: docker
      - image: mysql
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
      - image: postgres
    steps:
      - checkout
      - setup_remote_docker
      - run: docker info
      - run: docker build -t lolo/http-daemon-with-db http-daemon-with-db
      - run: docker run lolo/http-daemon-with-db --env
      - run: docker run --env "DATABASE_URL=mysql://" lolo/http-daemon-with-db
      - run: docker run --env "DATABASE_URL=postgresql://" lolo/http-daemon-with-db

workflows:
  version: 2
  docker:
    jobs:
      - mdl
      - flake8
      - build-go-ethereum
      - build-http-daemon-with-db
