version: 2
jobs:

  mdl:
    docker:
      - image: rsrchboy/mdl
    steps:
      - checkout
      - run: mdl .

  flake8:
    docker:
      - image: python
    steps:
      - checkout
      - run: pip install flake8
      - run: flake8 http-daemon-with-db

  build-go-ethereum:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t lolo/go-ethereum go-ethereum
      - run: docker run lolo/go-ethereum version

  build-http-daemon-with-db:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t lolo/http-daemon-with-db http-daemon-with-db
      - run: docker run lolo/http-daemon-with-db dump-env-vars

  test-http-daemon-with-mysql:
    docker:
      - image: lolo/http-daemon-with-db
      - image: circleci/mysql
      - image: circleci/postgres
    steps:
      - checkout
      - run: python project/http-daemon-with-db/main.py dump-env-vars
      - run:
          command: python project/http-daemon-with-db/main.py no-daemon
          environment:
            DATABASE_URL: "mysql://"
      - run:
          command: python project/http-daemon-with-db/main.py no-daemon
          environment:
            DATABASE_URL: "postgresql://"

workflows:
  version: 2
  docker:
    jobs:
      - mdl
      - flake8
      - build-go-ethereum
      - build-http-daemon-with-db
      - test-http-daemon-with-mysql:
          requires:
            - build-http-daemon-with-db
