version: 2
jobs:
  mdl:
    docker:
      - image: rsrchboy/mdl
    steps:
      - checkout
      - run: mdl .
  docker:
    docker:
      - image: docker
    steps:
      - checkout
      - run: docker info
      - run: docker build -t lolo/go-ethereum go-ethereum
      - run: docker run lolo/go-ethereum version
  flake8:
    docker:
      - image: python
    steps:
      - checkout
      - run: pip install flake8
      - run: flake8 http-daemon-with-db

workflows:
  version: 2
  docker:
    jobs:
      - mdl
      - docker
      - flake8
